export BITTREX_ACCOUNT=gaby
export CURRENCIES=BTG,POWR,CLUB,FTC,NXT,SBD,XZC,SWT,SLR,MER,NEO,GRS,TRIG,DASH,BAY,ARDR,SNT,POT,EMC2,XMR

export BITTREX_ACCOUNT=pablo
export CURRENCIES=ADA,TRIG,GRS,OK,IOP,RISE,VTC,NAV,MONA,ZEN,MCO,ADX,XLM,EMC2,XVG,SYS,XEL,EDG,KMD,STORJ

export BITTREX_ACCOUNT=staging

export PORTFOLIO_REPORT=False
export PORTFOLIO_TRADE=False
export PORTFOLIO_SIMULATING=False

